#############################################
# Fichier de configuration NAT-MOTD          #
# Par Nat0uille                             #
#############################################
# Tous les textes utilise le format MiniMessage, si vous utilisez autre chose ça fonctionnera pas !!!
# Pour créer vos messages, vous pouvez utiliser le site https://webui.advntr.dev/

Prefix: "<bold><gradient:#C70000:#951919>NAT-Lobby</gradient></bold> <gray>• "

OnJoin:
  # Choix disponibles : SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  Gamemmode : ADVENTURE
  # Message affiché au joueur lors de son arrivée dans le lobby
  # Choix disponibles : {prefix}, {player}, {online-players}, {max-players}
  Message: "{prefix}<#63c74d>+ <#5a6988>{player} <#63c74d>(<#5a6988>{online-players}<#63c74d>/<#5a6988>{max-players}<#63c74d>)"
  # Items dans la hotbar du joueur
  # 9 emplacements disponibles, de 0 à 8
  Items:
    1:
      Material: NETHER_STAR
      Name: "<green>Menu"
      Lore:
        - "<gray>Clique pour ouvrir le menu"
      Slot: 4
      # Choix disponibles : [PLAYER] : Commande exécuté par le joueur,
      #                     [CONSOLE] : Commande exécuté par la console,
      #                     [WORLD] téléporation a un endroit précis exemple : [WORLD] world 0 100 0
      Commands:
      - "[PLAYER] menu"
#    2:
#      Material: itemsadder:my_custom_item
#      Name: "<aqua>Custom IA"
#      Lore:
#        - "<gray>Item ItemsAdder depuis son id"
#      Slot: 0
#      Commands:
#      - "[PLAYER] ia-open"
  Teleport:
    World: "world"
    X: 0
    Y: 100
    Z: 0
    Yaw: 180
    Pitch: 0
  # Message affiché au joueur lors de son départ dans le lobby
  # Choix disponibles : {prefix}, {player}, {online-players}, {max-players}
OnQuit: "{prefix}<#ff0044>- <#5a6988>{player}} <#ff0044>(<#5a6988>{online-players}<#ff0044>/<#5a6988>{max-players}<#ff0044>)"

Commands:
  NoPermission: "<#C70000><bold>✖</bold> Vous n'avez pas la permission d'exécuter cette commande."
  Spawn: "<green>Vous avez été téléporté au spawn."
  SpawnConsole: "<red>Vous ne pouvez pas vous téléporter au spawn en étant la console."
  # Choix disponibles : {target} : Nom du joueur ciblé
  SpawnTargetSender: "<green>Vous avez téléporté {target} au spawn."
  # Choix disponibles : {target} : Nom du joueur ciblé
  SpawnTargetNotFound: "<red>Le joueur {target} n'a pas été trouvé."
  SetSpawn: "<green>Le spawn a été défini à votre position actuelle."
  SetSpawnConsole: "<red>Vous ne pouvez pas définir le spawn en étant la console."
  FlyDisabled: "<red>Le vol a été désactivé."
  FlyEnabled: "<green>Le vol a été activé."
  FlyConsole: "<red>Vous ne pouvez pas activer le vol en étant la console."
  # Choix disponibles : {target} : Nom du joueur ciblé
  FlyTargetSender: "<green>Vous avez changé le vol de {target}."
  # Choix disponibles : {target} : Nom du joueur ciblé
  FlyTargetNotFound: "<red>Le joueur {target} n'a pas été trouvé."
  BuildEnabled: "<green>Mode build activé. Vous êtes en créatif et pouvez utiliser votre hotbar."
  BuildDisabled: "<red>Mode build désactivé. Retour en adventure."
  BuildConsole: "<red>Vous ne pouvez pas activer le mode build en étant la console."

  NatLobby:
    Help: "<green>Menu d'aide</green>"
    Reload: "<green>Le plugin a été rechargé avec succès.</green>"